# Generated by Django 2.0.10 on 2019-03-03 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190222_1809'),
        ('documents', '0003_documents_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'permissions': (('can_view_create_documents', 'Views create documents'),)},
        ),
        migrations.AddField(
            model_name='documents',
            name='id_demand',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='myapp.Demand', verbose_name='Заявка'),
            preserve_default=False,
        ),
    ]
