# Generated by Django 2.0.10 on 2019-01-23 12:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания:')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200, verbose_name='Описание заявки:')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Количество:')),
                ('id_demand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Demand', verbose_name='Номер заявки: ')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Наименование позиции:')),
                ('art', models.CharField(max_length=15, verbose_name='Артикул:')),
                ('price_one', models.FloatField(verbose_name='Цена за 1 шт:')),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Product', verbose_name='Наименование товара:'),
        ),
    ]
